version: '3'
services:
  tarantool:
    image: tarantool/tarantool:2.8.0
    command: tarantool init.lua
    volumes:
      - $PWD/tarantool:/opt/tarantool:ro
    ports:
      - 3301:3301
    environment:
      TARANTOOL_USER_NAME: tokens
      TARANTOOL_USER_PASSWORD: tokens
